backend:
  name: github
  repo: PhilouLaudun/cantinphotonextjs 
  branch: main # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Home"
      name: "home"
      file: "content/home.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Soustitre", name: "soustitre", widget: "string" }
        - { label: "Footerhome", name: "footerhome", widget: "string" }
